### ISSUE TITLE
Better display of posts on front page

### ISSUE THREAD

**Issue by stpaultim** [backdrop-contrib/lateral#2]
I was just doing some testing of Lateral to see how it works out of the box. 

I spun up a DEMO site on Tugboat and did the following:

1) Enabled and made Lateral the default theme 
2) Added two posts with photos and edited the demo post to also have an image.

With an odd number of posts, the front page looks a little unusual. The borders around each item are inconsistent and the centering of the odd post at the bottom is a little unusual. 

RECOMMENDATION:

Lots of options. I suggest (some ideas):

1) More consistent use of borders
2) Either making the odd item at the bottom (on front page) float to the left and only take up 50% of the column OR have it stretch all the way across the page. 

![Home___Backdrop](https://user-images.githubusercontent.com/3144571/90972625-4cc4e200-e4e0-11ea-9751-7c719e99993b.png)

**Comment by indigoxela** [comment]
> With an odd number of posts, the front page looks a little unusual.

I see. Does the [latest commit](https://github.com/backdrop-contrib/lateral/commit/1220664b3a5f1cdbf5958bfa382baab7dc4e0c72) work for you?

**Comment by stpaultim** [comment]
Yes, this works much better. I tested it out on my sample site. This looks much better (in my opinion).

Thanks. Great theme.

![Simplo__](https://user-images.githubusercontent.com/3144571/90991923-294a7780-e572-11ea-8889-4526ea1e5665.png)

**Comment by indigoxela** [comment]
Fixed in v1.x-1.0.3. Many thanks for reporting this. :+1:
