### ISSUE TITLE
"initial" is too ambiguous for a select list background

### ISSUE THREAD

**Issue by indigoxela** [backdrop-contrib/lateral#3]
https://github.com/backdrop-contrib/lateral/blob/1220664b3a5f1cdbf5958bfa382baab7dc4e0c72/css/colors.css#L146

This can lead to unreadable text if the parent has a dark background.

**Comment by stpaultim** [comment]
I started to look into this issue last night, but got distracted. Nice to see that you were ahead of me anyway. Thanks for quick update.
