### ISSUE TITLE
Adding new font.

### ISSUE THREAD

**Issue by CyberSecGuy** [backdrop-contrib/lateral#4]
Hello! First off, I'm enjoying the Backdrop theme, but am having a strange issue. Maybe this more correctly should be posted on the Backdrop CMS issue tracker, however I'm using Lateral specifically so I'm going to start here.

I'm trying to add a new CSS Font through the General Settings (specifically: Comfortaa) but am having issues. Here are the following changes I'm making.

1)  **themes/lateral/theme-settings.php**
```
$form['settings']['font'] = array(
    '#type' => 'select',
    '#title' => t('Font'),
    '#default_value' => theme_get_setting('font', 'lateral'),
    '#options' => array(
      'opensans' => t('Open Sans'),
      'merriweather' => t('Merriweather'),
      'comfortaa' => t('Comfortaa'),  ## Added Comfortaa to the General Settings font drop down.
      'nowebfont' => t('No webfont'),
    ),
    '#description' => t('Use Open Sans for all text, or Merriweather for some (like headings), or only use a local system font (Arial)'),
  );
```

2) Created "comfortaa" folder under Fonts, and installed the following fonts;
```
comfortaa-v29-latin-300.eot    comfortaa-v29-latin-500.eot    comfortaa-v29-latin-600.eot    comfortaa-v29-latin-700.eot    comfortaa-v29-latin-regular.eot
comfortaa-v29-latin-300.svg    comfortaa-v29-latin-500.svg    comfortaa-v29-latin-600.svg    comfortaa-v29-latin-700.svg    comfortaa-v29-latin-regular.svg
comfortaa-v29-latin-300.ttf    comfortaa-v29-latin-500.ttf    comfortaa-v29-latin-600.ttf    comfortaa-v29-latin-700.ttf    comfortaa-v29-latin-regular.ttf
comfortaa-v29-latin-300.woff   comfortaa-v29-latin-500.woff   comfortaa-v29-latin-600.woff   comfortaa-v29-latin-700.woff   comfortaa-v29-latin-regular.woff
comfortaa-v29-latin-300.woff2  comfortaa-v29-latin-500.woff2  comfortaa-v29-latin-600.woff2  comfortaa-v29-latin-700.woff2  comfortaa-v29-latin-regular.woff2
```

Source: https://google-webfonts-helper.herokuapp.com/fonts/comfortaa?subsets=latin

3) Created comfortaa.css in the css/ folder and made modifications to it:
```
@font-face {
  font-family: 'Comfortaa';
  font-style: normal;
  font-weight: 400;
  src: url('../fonts/comfortaa/comfortaa-v29-latin-regular.eot'); /* Old IE */
  src:
    url('../fonts/comfortaa/comfortaa-v29-latin-regular.eot?#iefix') format('embedded-opentype'),
    url('../fonts/comfortaa/comfortaa-v29-latin-regular.woff') format('woff'),
    url('../fonts/comfortaa/comfortaa-v29-latin-regular.ttf') format('truetype'),
    url('../fonts/comfortaa/comfortaa-v29-latin-regular.svg#comfortaa-v29-latin-regular') format('svg');
}

@font-face {
  font-family: 'Comfortaa';
  font-style: italic;
  font-weight: 300;
  src: url('../fonts/comfortaa/comfortaa-v29-latin-300.eot'); /* Old IE */
  src:
    url('../fonts/comfortaa/comfortaa-v29-latin-300.eot?#iefix') format('embedded-opentype'),
    url('../fonts/comfortaa/comfortaa-v29-latin-300.woff') format('woff'),
    url('../fonts/comfortaa/comfortaa-v29-latin-300.ttf') format('truetype'),
    url('../fonts/comfortaa/comfortaa-v29-latin-300.svg#comfortaa-v29-latin-300') format('svg');
}

@font-face {
  font-family: 'Comfortaa';
  font-style: normal;
  font-weight: 700;
  src: url('../fonts/comfortaa/comfortaa-v29-latin-700.eot'); /* Old IE */
  src:
    url('../fonts/comfortaa/comfortaa-v29-latin-700.eot?#iefix') format('embedded-opentype'),
    url('../fonts/comfortaa/comfortaa-v29-latin-700.woff') format('woff'),
    url('../fonts/comfortaa/comfortaa-v29-latin-700.ttf') format('truetype'),
    url('../fonts/comfortaa/comfortaa-v29-latin-700.svg#comfortaa-v29-latin-700') format('svg');
}

@font-face {
  font-family: 'Comfortaa';
  font-style: italic;
  font-weight: 700;
  src: url('../fonts/comfortaa/comfortaa-v29-latin-700.eot'); /* Old IE */
  src:
    url('../fonts/comfortaa/comfortaa-v29-latin-700.eot?#iefix') format('embedded-opentype'),
    url('../fonts/comfortaa/comfortaa-v29-latin-700.woff') format('woff'),
    url('../fonts/comfortaa/comfortaa-v29-latin-700.ttf') format('truetype'),
    url('../fonts/comfortaa/comfortaa-v29-latin-700.svg#comfortaa-v29-latin-700') format('svg');
}

body {
  font: 1rem/1.6 verdana, sans-serif;
}
button,
input,
optgroup,
select,
textarea {
  font: 1rem/1.6 verdana, sans-serif;
}
.site-name,
ul.menu,
.block-hero,
h1, h2, h3, h4, h5, h6 {
  font-family: 'Comfortaa';
}
```

Having said all that; the font will not change to Comfortaa, it remains Arial or what ever the default is. The font DOES change when moving between Open Sans and Merriweather.

Any assistance would be wonderful, thank you!

**Comment by CyberSecGuy** [comment]
Issue appears to be resolved.

I did **NOTHING** and went for dinner, giving it about an hour since last attempt, and it appears to have worked. I suspect this is a cloudflare caching issue and it just updated.

Marked resolved, and for anyone else feel free to do what I did to include a new font.

**Comment by indigoxela** [comment]
@CyberSecGuy glad that it worked for you.

One important notice: you should *not* edit the contrib theme (in lateral directory) directly. Your changes will be lost with the next  theme update. You should rather create a custom subtheme. Just ask if you need help with that.

**Comment by CyberSecGuy** [comment]
> Just ask if you need help with that.

If you recommend that as the appropriate way to initiate this change, then yes please. Also; if you don't mind, I would like to possibly submit this to the main branch? Any way I can do that to add Comfortaa as a font option, I personally just really enjoy the font.

**Comment by indigoxela** [comment]
> if you don't mind, I would like to possibly submit this to the main branch?

Comfortaa is a pretty font, but I don't want to add yet another one to lateral. I'll rather help you with creating a subtheme:

Here's the documentation: https://api.backdropcms.org/documentation/creating-sub-themes

The magic starts with `base theme = lateral` in the info file. Then you only have to add what you want to override, the rest still gets provided by the base theme.

This is the structure of your subtheme:
[lateral_sub.zip](https://github.com/backdrop-contrib/lateral/files/5753739/lateral_sub.zip)

Download it and unzip it in the theme directory of your Backdrop install, enable it and set as default (on admin/appearance).
Add the Comfortaa webfonts to the fonts directory of lateral_sub and you should be done.

**Comment by CyberSecGuy** [comment]
Excellent, thank you! I'll work on this over the weekend.

Edit: worked perfectly, thanks!
