### ISSUE TITLE
Tables way too narrow

### ISSUE THREAD

**Issue by PepeMty** [backdrop-contrib/lateral#5]
I'm trying to build some sort of personal and private website for a small family business and this gorgeous theme is just what I need.

Thing is that tables are way too narrow, be them calendars via the fullcalendar module or simple views tables.

Can somebody point me in the right direction...?

Warm regards from sunny México.

Thanks...!

**Comment by indigoxela** [comment]
Ouch... that's a nasty side effect of the responsive table style. It's probably best to remove that.

**Comment by indigoxela** [comment]
Should be fixed in 1.x-1.0.5

**Comment by PepeMty** [comment]
It is fixed...!
Thanks a lot.
