### ISSUE TITLE
Changes to front page with new Cards

### ISSUE THREAD

**Issue by stpaultim** [backdrop-contrib/lateral#7]
FYI - I'm doing screenshots of the front page of sites with various contrib themes after the new Card content type is added to core. 

![lateral-cards](https://user-images.githubusercontent.com/3144571/165409403-e22e0ee6-2c8f-46fd-b04c-92ecc369f240.png)

**Comment by indigoxela** [comment]
Should be fixed in https://github.com/backdrop-contrib/lateral/releases/tag/1.x-1.0.6
