### ISSUE TITLE
Make it easier to change Hero Images - or provide instructions

### ISSUE THREAD

**Issue by stpaultim** [backdrop-contrib/lateral#8]
This is a great theme and I think it would be greater if it were easy for a site admin to upload their own hero image. 

Short of this, at least provide some instructions that make it clear how they could modify the theme to add a custom image. 

I'm providing a PR with a rough idea of how this might be done at it's simplest, but I'm sure you could do better. My PR is quite simple and does two things. 

1) Adds some text to README that addresses this question, which I expect many users will have. 
2) Move relevent css to top of the file to make it easy for a user to find and edit. You might even create a custom css file things that users are most likely to change.

**Comment by indigoxela** [comment]
Ouch, this change is very, very misleading.

As soon as we even encourage people to change the CSS files **directly** - without a subtheme - they will do, which will make future updates of that contrib theme impossible.

The **proper** way to change the image is: upload one via layout UI, in the block dialog.
I'd never encourage people to hack code that might need updates at some point. Not in core, not in contrib.

**Comment by stpaultim** [comment]
Well, the point I'm making is that if there is a proper way to do it, why not mention that in the Readme. 

I looked first for some documentation for how to do this, but couldn't find any. So, I started to make up stuff.

I'm not having a very good night for getting things right.

:-(

**Comment by indigoxela** [comment]
> the point I'm making is that if there is a proper way to do it, why not mention that in the Readme

That's a good idea. :+1: We shouldn't assume, that people are already familiar with layouts and blocks, when they try out contrib themes.

**Comment by stpaultim** [comment]
I just did it the right way and that's MUCH better. 

But, it was not at all clear to me that would work until you told me it would. On a better day, I might have thought to try it myself, but not today.

**Comment by stpaultim** [comment]
This is such a nice theme. Good work.

**Comment by stpaultim** [comment]
![image](https://github.com/backdrop-contrib/lateral/assets/3144571/ba4398ac-2c99-4c11-936c-40ea7a4a4d73)

**Comment by indigoxela** [comment]
Currently the readme is pretty sparse...

Some help with explaining things better would be highly appreciated - doesn't have to be today/tonight. :smiley:
